run:
  timeout: 15m
  exclude-dirs:
  - .git
  - .tool
  - vendor
  - verify

linters-settings:
  dupl:
    threshold: 100
  gocyclo:
    min-complexity: 50
  govet:
    enable:
      - nilness
  revive:
    rules:
      # https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#duplicated-imports
      - name: duplicated-imports
        severity: warning

linters:
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errorlint
    - gocritic
    - gosimple
    - govet
    - ineffassign
    - intrange
    - misspell
    - nolintlint
    - nosprintfhostport
    - revive
    - staticcheck
    - tenv
    - unconvert
    - unused
    - wastedassign
  disable-all: true

issues:
  exclude:
  - singleCaseSwitch # in most cases this is the beginning of a lookup table and should be kept an obvious table
  exclude-rules:
  - linters:
    - staticcheck
    # TODO: Is this really supposed to be deprecated? Ref https://github.com/kubernetes/test-infra/issues/14875
    text: "SA1019: t.*.TrustedOrg is deprecated: TrustedOrg functionality is deprecated and will be removed in January 2020"
